site_name: Professional course
nav: 
    - 计算机组成原理:
        - computer organization&architecture/1.COA概述.md
        - computer organization&architecture/2.Basic CO&&Design.md
        - computer organization&architecture/3.Computer Instructions.md
        - computer organization&architecture/4.Digital Logic Circuits.md
        - computer organization&architecture/5.Combinational Circuits.md
        - computer organization&architecture/6.Flip - Flops.md
        - computer organization&architecture/7.Digital Components.md
        - computer organization&architecture/8.Register Transfer language.md
        - computer organization&architecture/9.Micro-Operations.md
        - computer organization&architecture/10.Memory Organization.md
        - computer organization&architecture/11.Pipeline.md
        - computer organization&architecture/Misc.md
    - 计算机网络:
        - computer network/1.概述.md
        - computer network/2.Models.md
        - computer network/3.Physical Layer.md
        - computer network/4.Data Link layer.md
        - computer network/5.Network Layer.md
        - computer network/6.Routing Algorithm.md
        - computer network/7.Transport Layer.md
        - computer network/8.Application Layer.md
        - computer network/9.Application Protocols.md
        - computer network/10.Network Security.md
        - computer network/Misc&MCQ.md
    - 操作系统:
        - operating system/1.概述.md
        - operating system/2.Process Management.md
        - operating system/3.Synchronization.md
        - operating system/4.Deadlocks.md
        - operating system/5.Memory Management.md
        - operating system/6.File Management.md
        - operating system/Misc&MCQ.md
    - 数据结构:
        - data structure/1.概述.md
        - data structure/2.Array.md
        - data structure/3.Linked List.md
        - data structure/4.Stack.md
        - data structure/5.Queue.md
        - data structure/6.Tree.md
        - data structure/7.Graph.md
        - data structure/8.Searching.md
        - data structure/9.Sorting.md
        - data structure/10.Differences.md
        - data structure/Misc&MCQ.md
    - 刻意练习:
        - 刻意练习\0.序.md
        - 刻意练习\1.有目的的练习.md
        - 刻意练习\2.大脑的适应能力.md
        - 刻意练习\3.心里表征.md
        - 刻意练习\4.黄金标准.md
        - 刻意练习\5.在工作中运用刻意练习原则.md
        - 刻意练习\6.在生活中运用刻意练习原则.md
        - 刻意练习\7.成为杰出人物的路线图.md
        - 刻意练习\8.怎样解释天生才华.md
        - 刻意练习\9.用刻意练习创造全新世界.md
    - 工程:
        - 工程/0.整体介绍.md
        - 工程/1.概述.md
        - 工程/2.数据绑定.md
        - 工程/3.过渡&动画.md
        - 工程/data warehouse.md
        - 工程/sql.md
        - 工程/software engineering.md
        - 工程/github.md
extra_css:
    - res/extra.css
extra_javascript:
    - res/extra.js

    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js

    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2022 - 2023 travis

# repo_url: @
# repo_name: @

theme:
    name: material
    # custom_dir: overrides

    palette:
        - media: "(prefers-color-scheme)"
          primary: red
          accent: red
          toggle:
            icon: material/brightness-auto
            name: 切换到暗模式
        - media: "(prefers-color-scheme: light)"
          primary: green
          accent: green
          scheme: default 
          toggle:
            icon: material/brightness-7
            name: 切换到默认模式
        - media: "(prefers-color-scheme: dark)"
          primary: blue
          accent: blue
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: 切换到亮模式

    font:
        text: Roboto
        code: Roboto Mono

    language: zh
    direction: ltr

    logo: https://static.javatpoint.com/tutorial/coa/images/coa-tutorial.png
    favicon: https://static.javatpoint.com/tutorial/coa/images/coa-tutorial.png
    icon:
        logo: octicons/heart-fill-24

        repo: fontawesome/brands/github
        edit: material/pencil
        view: material/eye


        admonition:
            note: fontawesome/solid/note-sticky
            abstract: fontawesome/solid/book
            info: fontawesome/solid/circle-info
            tip: fontawesome/solid/bullhorn
            success: fontawesome/solid/check
            question: fontawesome/solid/circle-question
            warning: fontawesome/solid/triangle-exclamation
            failure: fontawesome/solid/bomb
            danger: fontawesome/solid/skull
            bug: fontawesome/solid/robot
            example: fontawesome/solid/flask
            quote: fontawesome/solid/quote-left




    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        # - navigation.expand
        - navigation.prune
        - navigation.indexes
        - toc.follow
        # - toc.integrate
        - navigation.top

        - search.suggest
        - search.highlight
        - search.share

        - header.autohide

        - navigation.footer

        - content.action.edit
        - content.action.view

        - content.code.copy
        - content.code.annotate

        - content.tooltips


extra:
    alternate:
        - name: 计算机组成原理
          link: https://www.javatpoint.com/computer-organization-and-architecture-tutorial 
          lang: en
        - name: 计算机网络
          link: https://www.javatpoint.com/computer-network-tutorial
          lang: zh
        - name: vue.js官网
          link: https://vuejs.org/ 
          lang: en
        - name: vue.js游乐场
          link: https://play.vuejs.org/#eNo9jcEKwjAMhl/lt5fpQYfXUQfefAMvvRQbddC1pUuHUPrudg4HIcmXjyRZXEM4zYlEJ+T0iEPgXjn6BB8Zhp46WUZWDjCa9f6w9kAkTtH9CRinV4fmRtZ63H20Ztesqiylphqy3R5UYBqD1UyVAPk+9zkvV1CKbCv9poMLiTEfR2/IXpSoXomqZLtti/IFwVtA9A==
          lang: zh
        - name: vue.js官方教程
          link: https://vuejs.org/guide/quick-start.html#try-vue-online
          lang: zh
        - name: vue.js官方中文教程
          link: https://cn.vuejs.org/tutorial/#step-1
          lang: zh

    homepage: /

    #consent:
    #    title: cookie
    #    description:    >-
    #        sdd
    #    cookies:
    #        analytics:
    #            github


    social:
        - icon: fontawesome/brands/github
          link: 链接url地址
          name: 标识名
        - icon: fontawesome/brands/docker
          link: 链接url地址
          name: 标识名
    generator: false


plugins:
    - search:
        lang:
            - en
            - ja
        # '[\s\-,:!=\[\]]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
        separator: '[\s\-\.]+'
        jieba_dict: res/dict.txt
        jieba_dict_user: res/user_dict.txt
    - search:
        lang:
            - en
        jieba_dict: dict/dict.txt
        separator: '[\s\-\.]+'
    # - typeset

    - glightbox

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

    - attr_list
    - md_in_html
    - pymdownx.superfences

    - attr_list

    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    #- pymdownx.tabbed:
    #    slugify: !!python/object/apply:pymdownx.slugs.slugify
    #        kwds:
    #            case: lower

    # - content.tabs.link


    - tables
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes

    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde

    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg


    - attr_list
    - md_in_html

    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true

    - pymdownx.arithmatex:
        generic: true

    - abbr
    - attr_list
    - pymdownx.snippets
    - pymdownx.snippets:
        auto_append:
            - includes/abbr.md

